### ISSUE TITLE
Set rating on tap

### ISSUE THREAD

**Issue by JBenzie** [marketplacer/Cosmos#19]
I may be doing something wrong, but currently I can only set the rating by touching and sliding from left to right. I cannot simply tap a star to set the rating. If this is possible, how is it implemented?

Thanks,
Jerry

**Comment by evgenyneu** [comment]
Hi Jerry, this is interesting. The rating should change either on tap or swipe, it should not matter. Do you have this problem in the demo app of this repository as well?

**Comment by JBenzie** [comment]
I could have easily missed something in my implementation. I'll give the demo app a try and go back over my code. I just wanted to verify that this was possible.

Thank you

**Comment by mnimants** [comment]
Hi!

I'm facing the problem (or maybe it's intended behaviour?) that ratings only update on either swipe or long tap - I would like it to update on just normal tap. Should it be like that?

**Comment by mnimants** [comment]
The problem was that one of the superviews had uitapgesturerecognizer and cosmosview wasn't receiving taps.
