### ISSUE TITLE
Question: presenting cosmos as an alert

### ISSUE THREAD

**Issue by oferRounds** [marketplacer/Cosmos#22]
I'm wondering what would be the easiest way

Thanks for this library - seems great!

**Comment by evgenyneu** [comment]
Hi @oferRounds, good question. One way to do it is to have a hidden view containing cosmos that is shown when needed.

Here is a demo: 
[UsingCosmosInOverlay.zip](https://github.com/marketplacer/Cosmos/files/218442/UsingCosmosInOverlay.zip)


![persenting_cosmos_in_overlay](https://cloud.githubusercontent.com/assets/880411/14517998/bb8fb258-0256-11e6-98a6-1f9e9a110718.png)

**Comment by oferRounds** [comment]
Hi @evgenyneu - looks good!
Thanks for this and for the library itself!
