### ISSUE TITLE
Error when load it to TableView

### ISSUE THREAD

**Issue by khuong291** [marketplacer/Cosmos#23]
I drag a view and set its class to CosmosView, but when I run the project, it crashes:

> Failed to set (rateLineWidth) user defined inspected property on (Cosmos.CosmosView): [<Cosmos.CosmosView 0x7ff150d53e70> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key rateLineWidth.

**Comment by evgenyneu** [comment]
Hello, @khuong291. I think I had similar problem in the past and solved by clearing "User defined runtime attributes" for the cosmos view (shown in the screenshot).

I have also made a quick test and put cosmos in a table view, could not reproduce your issue (see the attached demo project).

Let me know how it goes.

[UsingCosmosInTableView.zip](https://github.com/marketplacer/Cosmos/files/222445/UsingCosmosInTableView.zip)
 
<img width="493" alt="runtime_attributes" src="https://cloud.githubusercontent.com/assets/880411/14584280/cb344624-0481-11e6-8eba-009b11e119bd.png">

**Comment by khuong291** [comment]
I have not tried your example project yet. But now It works well. 

![screen shot 2016-04-17 at 10 56 33 am]

Thanks @evgenyneu. +1 ⭐  👍 
(https://cloud.githubusercontent.com/assets/11523438/14584961/232ba832-048b-11e6-9bcb-84b8aa5830ad.png)

**Comment by evgenyneu** [comment]
I am glad it worked. Feel free to comment if you have any other issues. Have a good day.

**Comment by khuong291** [comment]
Can I ask one more question: Is CosmosView Rating max  = 5

**Comment by khuong291** [comment]
I think it would more covenient if you can add one more choice like so:
cosmosView.ratingWithRatio(starCount: 5, maxRating: 100) = 90
So the CosmosView will have 4.5 star. 😸

**Comment by evgenyneu** [comment]
Sorry, I do not understand your question. Can you give me an example of what you want to achieve in your app?

**Comment by khuong291** [comment]
For example, I want to rating a movie, its rating has 94/100 point, So I the CosmosView.rating should be 94*5/100 = 4.7 if I want maximum with 5 star.

So If I want to use with 10 star, it should be 94*10/100 = 9.4.

I just recomend for you to implement more 😄

**Comment by khuong291** [comment]
Oh, sorry, you have done with it. My fault.

**Comment by evgenyneu** [comment]
I do value your recomendations, @khuong291. I just wanted to understand what you meant.
Did you want Cosmos to show ten stars with rating 9.4? If so you can currently do it like this:

```Swift
cosmosView.settings.totalStars = 10
cosmosView.settings.fillMode = .Precise // Others are .Half and .Full
cosmosView.rating = 9.4
```

Or you can do it from the Storyboard as well:

<img width="739" alt="ten_stars" src="https://cloud.githubusercontent.com/assets/880411/14585881/099aadbc-04c9-11e6-9653-ee5be56c33c6.png">


This is described in the [configuration manual](https://github.com/marketplacer/Cosmos/wiki/Cosmos-configuration).

And thank you very much for the feedback.

**Comment by khuong291** [comment]
Yes, I don't read your guide carefully, sorry. Your project is awesome 👍

**Comment by MasterHM-ios** [comment]
> Hello, @khuong291. I think I had similar problem in the past and solved by clearing "User defined runtime attributes" for the cosmos view (shown in the screenshot).
> 
> I have also made a quick test and put cosmos in a table view, could not reproduce your issue (see the attached demo project).
> 
> Let me know how it goes.
> 
> [UsingCosmosInTableView.zip](https://github.com/marketplacer/Cosmos/files/222445/UsingCosmosInTableView.zip)
> 
> <img alt="runtime_attributes" width="493" src="https://cloud.githubusercontent.com/assets/880411/14584280/cb344624-0481-11e6-8eba-009b11e119bd.png">

this solution solved my problem. thanks
cleared user defined attributes from storyboard
