### ISSUE TITLE
not exist cosmos

### ISSUE THREAD

**Issue by J-Arji** [marketplacer/Cosmos#24]
hello @evgenyneu evgeny
when I Set the view's class to CosmosView in the Identity Inspector .
`warning: IB Designables: Using class UIView for object with custom class because the class CosmosView does not exist`
 Because you know it ?

**Comment by evgenyneu** [comment]
Hi, hmm looks like it can not find the Cosmos module. Did you set Cosmos in the "Module" field ?

**Comment by J-phantom** [comment]
yes. but not working

**Comment by evgenyneu** [comment]
I see, which one of the setup methods did you use? Carthage, Cocoa Pods or CosmosDistrib.swift file?

**Comment by evgenyneu** [comment]
Hi @J-Arji, was the problem fixed for you?

**Comment by J-Arji** [comment]
hi @evgenyneu .
Yes .thank you  :)
