### ISSUE TITLE
Can't get Tap Gesture UIState Began 

### ISSUE THREAD

**Issue by gurkarangulati** [marketplacer/Cosmos#26]
I needed to know when the cosmo stars are being pressed to caused other things in the view to happen. It seems when you add a UITapGestureRecognizer on the CosmoView you only get Ended and don't get began. Amazing job otherwise.

`let gestureViewCosmoTapped: UITapGestureRecognizer = UITapGestureRecognizer(target: self, action: #selector(ViewController.tapGestureViewCosmo))

func tapGestureViewCosmo(sender: UITapGestureRecognizer){
        print("Tap : " + String(sender.state.rawValue))
        if (sender.state == UIGestureRecognizerState.Ended){
            print("ended")
        }else if (sender.state == UIGestureRecognizerState.Changed){
            print("changed")
        }else if (sender.state == UIGestureRecognizerState.Began){
            print("began")
        }else if (sender.state == UIGestureRecognizerState.Cancelled){
            print("cancelled")
        }else{
        }
    }`

**Comment by gurkarangulati** [comment]
All View's don't allow this on UITapGestureRecognizer.

**Comment by evgenyneu** [comment]
Hi, @gurkarangulati, I see that you closed the issue. Has it been sorted out? Or do you still have any issues?

**Comment by gurkarangulati** [comment]
Hello Evgenii,

Yeah I realized any view you do that to you never get the began state. It
wasn't specific to the CosmoView. Thanks so much tho!

Best,
Gurkaran
