### ISSUE TITLE
Having trouble getting stars to show

### ISSUE THREAD

**Issue by CTJyeh** [marketplacer/Cosmos#30]
I am putting a View inside a TableViewCell via storyboard. I've set the width of the view to 60, height to 20. 
I set the view to class ComosView, and via the attribute inspector, I set 
Rating: 5, text 0, total Stars 5, star size 20. 
Filled colors, empty colors...etc.  

However,  when i run it in the simulator, (i expect to see 5 stars filled).  But the view is empty.  
I have no idea why.  What might I be doing wrong? 

Secondary question, I've also tried to set rating programatically when configuring the tableviewcell, however, I get a exc_bad_access.

**Comment by evgenyneu** [comment]
Hi @CTJyeh, thanks for reporting. Did you try a simple case of using Cosmos view without a table view? 

There is no need to specify width and height of the view, they will be automatically determined based on the size of the stars.

The demo app contains a screen that shows how to use Cosmos in a table view. You may want to look at this example.

Let me know how it goes.

**Comment by CTJyeh** [comment]
nvm, i figured out what I was doing wrong. 
I forgot to set the module field when setting custom class to Cosmos. 
Sorry for the confusion.  Thanks! this is working! .

**Comment by evgenyneu** [comment]
No worries at all and good luck.
