### ISSUE TITLE
Cosmos not "touching" in tableviewcell

### ISSUE THREAD

**Issue by niclego** [marketplacer/Cosmos#31]
Hi! i set up a tableviewcell with a few components including a cosmos view. At first i was able to get feedback using the didFinishTouchingCosmos function on my cell after i called the dequeueReusableCellWithIdentifier. But for some reason now, the cosmos interaction has seemed to have been turned off. Any idea why this is happening?

**Comment by evgenyneu** [comment]
Hello, @niclego. Thanks for the feedback. I would check two things first

1. `cosmosView.settings.updateOnTouch = true`
2. *User Interaction enabled* on the cosmos view in the storyboard.

Also, the demo app has a screen with cosmos views in a table. The `updateOnTouch` is set to `false` deliberately there, but you can set it back to `true` and verify that it is working for you (it did for me).

Let me know how it goes.

**Comment by niclego** [comment]
Yeah I did that. But I think it was something weird with the cosmos view
being behind the default view that table cells have. So I ended up
converting all my table views into collection views and all the table cells
into collection cells. Now cosmos is working.

Thanks for your response!
Nick

**Comment by evgenyneu** [comment]
I am glad you found a solution, thanks for sharing!

**Comment by evgenyneu** [comment]
Closing this issue, feel free to reopen if needed.
