### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by SMFakhir** [marketplacer/Cosmos#32]
![screen shot 2016-06-30 at 7 18 32 pm](https://cloud.githubusercontent.com/assets/7599643/16491489/97f78c02-3ef7-11e6-8d2e-3a7ee7cf571d.png)

**Comment by evgenyneu** [comment]
Hi @SMFakhir, thank you for reporting. The current version of Cosmos is written in Swift 3.0. If you are using an older version of Swift please refer to these setup instructions. https://github.com/marketplacer/Cosmos/wiki/Legacy-Swift-versions

Let me know how if it works for you.

**Comment by SMFakhir** [comment]
Surprised. its not even publicly released yet and you updated this repo for it.
Thanks, Its working now.

**Comment by evgenyneu** [comment]
Yes, Cosmos is at the frontier of discovery. 😃 I am glad it is working now. I will keep the issue open for now for other people. Cheers.

**Comment by evgenyneu** [comment]
Closing, feel free to reopen when needed.
