### ISSUE TITLE
Can't change value of cosmos

### ISSUE THREAD

**Issue by yigitserin** [marketplacer/Cosmos#34]
Similar to #31, I have a CosmosView inside a UITableViewCell. Normally it works fine. 

However, when I add a UITapGestureRecognizer to my UITableView, I can no longer change the value of CosmosView by tapping.

I have to hold touch on CosmosView to actually work after adding the UITapGestureRecognizer.

I am using UITapGestureRecognizer for dismiss keyboard functionality. And this is how I add UITapGestureRecognizer.

```
        let tapQuit = UITapGestureRecognizer(target: self, action: #selector(FeedTableViewController.dismissKeyboard(_:)))
        tableView.addGestureRecognizer(tapQuit)
```

I have also enabled `cosmosview.settings.updateOnTouch = true`

So my question is, is there any way to make it work with UITapGestureRecognizer. Or should I just get rid of UITapGestureRecognizer, and try to solve dismiss keyboard with some other way?

Thanks!

**Comment by evgenyneu** [comment]
Hi @yigitserin, thank you for interesting question. This may help to keep the touches reaching the Cosmos.

```Swift
tapQuit.cancelsTouchesInView = false
```

Let me know if it works for you.

**Comment by yigitserin** [comment]
Thanks it worked perfectly!
