### ISSUE TITLE
How To save Ratings in variables? 

### ISSUE THREAD

**Issue by bigpapa86** [marketplacer/Cosmos#36]
Hi,

Could you provide a short example on how to use didFinishTouchingCosmos and save values in variables?
It is not very clear to me in the read me file, sorry.

thanks,

**Comment by evgenyneu** [comment]
Hi @bigpapa86 (cool nickname), thanks for the question.

To save a rating you can supply a closure like this:

```Swift
cosmosView.didFinishTouchingCosmos = { rating in
    // Save the rating here (local database, send to server etc.)
}
```

The details of saving the rating depend on your app implementation. Is that what you were asking?

**Comment by bigpapa86** [comment]
Thank you @evgenyneu for the reply, I am glad you like the nickname :)

The issue is I don't understand closures very well (apple documentation is like hell lol), I will try the function method it looks more common to me.

I have multiple rates in the same page, I will do a function for each one and save it in its variable.
then I will send all the variables to server in a separate function. am sure its not the smartest approach but will do for now :)

Thank you bro for your support and for the great cosmos you provided, Keep it up :)

**Comment by evgenyneu** [comment]
You method sounds great to be. Good luck.
