### ISSUE TITLE
Swift 2.3 support (branch)

### ISSUE THREAD

**Issue by Lukafin** [marketplacer/Cosmos#39]
Hi

Are you planning to have a new branch for Swift 2.3?

Thank you.

**Comment by evgenyneu** [comment]
Hi @Lukafin, good question. We were not planning to do this, unfortunately. But anyone is feel free to submit a pull request. One needs to checkout tag `1.2.3`, this is Swift 2.2 version and convert it to Swift 2.3 in a separate branch.

**Comment by Lukafin** [comment]
Ok. 
I made a new swift2.3 branch locally from 1.2.3 tag. Can you add me as a collaborator so i can push the new branch and make a pull request. 
Thanks.

**Comment by evgenyneu** [comment]
Thank you, @Lukafin. I have merged your changes to `swift-2.3` branch. Here are the setup instructions:

https://github.com/marketplacer/Cosmos/wiki/Legacy-Swift-versions#swift-23

**Comment by evgenyneu** [comment]
Closing the issue, feel free to open if needed.
