### ISSUE TITLE
Is it possible to allow zero rating?

### ISSUE THREAD

**Issue by bigpapa** [marketplacer/Cosmos#45]
Hi Evgenii Neumerzhitckii,

I wonder is there a way to allow zero star rating? 

Thanks,

**Comment by evgenyneu** [comment]
Hi @bigpapa, yes, you can do it by setting the `minTouchRating` to zero:

```Swift
  cosmosView.minTouchRating = 0
```

Or, you can do it from the storyboard:

<img width="694" alt="cosmos_zero_rating_2" src="https://cloud.githubusercontent.com/assets/880411/18935899/89a76656-8626-11e6-833e-5fa9918ad1e0.png">


### Demo

<img width="150px" src="https://cloud.githubusercontent.com/assets/880411/18935870/483e6dfe-8626-11e6-95ab-33422cb48584.gif" alt="cosmos view with zero rating">

**Comment by bigpapa** [comment]
thank you very much Evgenii Neumerzhitckii,
Great support as always :) 

Best Regards,

**Comment by evgenyneu** [comment]
No worries, thanks for asking. Your question will be useful for other people who are looking for the same answer. All the best.
