### ISSUE TITLE
Readme wrong re: Swift 2.3 branch?

### ISSUE THREAD

**Issue by amitmaor** [marketplacer/Cosmos#48]
Hi there,

Thanks so much for this awesome library!

My company is still using swift 2.3, and adding `github "marketplacer/Cosmos" ~> 1.2` to the Cartfile did not work. It did work when I added `github "marketplacer/Cosmos" "swift-2.3"`, however, so I don't think the branch itself is the issue. Is there possibly a typo in the readme regarding the version number?

Thanks in advance!

**Comment by evgenyneu** [comment]
Hello @amitmaor, thanks for the feedback. I could not find the place in the README that mentions the Swift 2.3 version. Sorry, which README file do you mean?

There is a [Legacy Swift versions](https://github.com/marketplacer/Cosmos/wiki/Legacy-Swift-versions#swift-23) with the setup instructions for the Swift 2.3. However, the version `1.2` mentioned there is for Swift 2.2. Am I looking at the wrong place?

**Comment by amitmaor** [comment]
Hi @evgenyneu, I went to [the swift-2.3 branch](https://github.com/marketplacer/Cosmos/tree/swift-2.3) and looked at the `Setup with Carthage` instructions which are in the `README.md` file on that page, saying to use version 1.2.

**Comment by amitmaor** [comment]
I should note I got it to work using `github "marketplacer/Cosmos" "swift-2.3"` so I found a solution for my case, just wanted to make sure the readme is accurate for others!

**Comment by evgenyneu** [comment]
Oh, you are right, the branch was using wrong instructions. Thanks for pointing this out, fixed.
Yes, you can point your podfile directly to the branch as well. I am glad it worked for you.
