### ISSUE TITLE
Xcode 8.1 - Swift 3.0.1 support

### ISSUE THREAD

**Issue by alexvndre** [marketplacer/Cosmos#49]
Hi,

There is a support for these versions (Xcode 8.1 - Swift 3.0.1)?

I have this error:
```
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
```

Thanks!

**Comment by evgenyneu** [comment]
Hello @alexvndre, thank you for reporting. I have tested the latest version of the library in Xcode 8.1 (8B62) with CocoaPods `1.1.1` and did not see any errors. Am I missing something?

Here is a demo project:

[UsingCosmos.zip](https://github.com/marketplacer/Cosmos/files/596618/UsingCosmos.zip)

**Comment by alexvndre** [comment]
I updated CocoaPods and it's work! Thanks.

**Comment by evgenyneu** [comment]
No worries, I am glad it worked for you.
