### ISSUE TITLE
Selecting by swipe

### ISSUE THREAD

**Issue by moonvader** [marketplacer/Cosmos#51]
Thank you for this nice and simple UI item!

What setting should I use in order to enable selecting star by swipe. Right now I can use selection of only by tapping one of stars

**Comment by evgenyneu** [comment]
Thanks, @moonvader, I am glad you liked it. Sorry, could you elaborate exactly what you mean by swipe? Where do you put your finger and how you move it relative to the Cosmos view? What do you expect to happen?

**Comment by moonvader** [comment]
I expect that when I moving finger over stars - stars would be filled accordingly. But as I moving my finger over stars - nothing happens until i press one of stars directly. I hope that I explaining it clear.

**Comment by evgenyneu** [comment]
Yes, you are right, the star rating is supposed to change when you move your finger without lifting. If that is not happening it means something is not working correctly.

A question. When you do the swipe, let's say the gesture consists of three parts:

1. Touch the screen.
2. Move you finger.
3. Lift up the finger from the screen.

When you do step #1 "touch the screen", where do you touch it in relation to the cosmos view? Do you touch within cosmos view or outside it?

**Comment by moonvader** [comment]
@evgenyneu, thank you 
First of all - I found out that this problem occurs when I put Cosmos inside popup dialog (https://github.com/Orderella/PopupDialog). So if I turn off "gesture Dismissal" option of popup dialog - everything is fine. 
Also if I just add Cosmos to UIViewController - everything works fine.
So it is of course not issue with you code - but maybe you can suggest how can I use it without disabling gesture dismissal?

**Comment by evgenyneu** [comment]
I am glad you found out what was causing the problem. Maybe PopupDialog creates a gesture recognizer that cancels touches in the view, that prevents the swipes to be passed to the cosmos view. Setting `gesture.cancelsTouchesInView = false` might help, but you need to have access to the gesture recognizer object of the PopupDialog library. I would suggest asking the library maintainers about that. All the best.
