### ISSUE TITLE
Does not compile from within an Extension

### ISSUE THREAD

**Issue by moritzsternemann** [marketplacer/Cosmos#53]
When compiling from within an extension (e.g. a Notification Content Extension), `UIApplication.shared` is not available and the compiler throws an error in [RightToLeft.swift]()

    ...Cosmos/Helpers/RightToLeft.swift:14:28: 'shared' is unavailable: Use view controller based solutions where appropriate instead.

**Comment by evgenyneu** [comment]
Hi @moritzsternemann, thanks for reporting. Which version of Cosmos are you using? This problem was fixed in the most recent version `8.0.2`. Let me know if it works for you.

**Comment by moritzsternemann** [comment]
Sorry, my bad. I was using `8.0.1`. Thanks for helping me out 😄
