### ISSUE TITLE
is there any didTouchFinish?!

### ISSUE THREAD

**Issue by zigool** [marketplacer/Cosmos#7]
hi.
thank for your great work.
how i can know if touch is finished?
i want to send selected rate to server after user set the rate.
i used didTouchCosmos,but it is not good way to send rated value to server!

**Comment by evgenyneu** [comment]
Hi @zigool, this is actually a really useful suggestion that I will use in my own app.
Implemented, thanks!

```Swift
// Called when user finishes changing the rating by lifting the finger from the view.
// This may be a good place to save the rating in the database or send to the server.
cosmosView.didFinishTouchingCosmos = { rating in }
```

**Comment by zigool** [comment]
hey man!
Thanks
i'm using Xcode 6 and swift 1.2 and cocoapods!
there is not any 'didFinishTouchingCosmos'
how i should update library in my project?!
sorry i'm beginner in ios

**Comment by evgenyneu** [comment]
No worries. Yes you will need to upgrade to Xcode 7 to get this update.
