### ISSUE TITLE
Changelog File

### ISSUE THREAD

**Issue by mctavishsolutions** [marketplacer/Cosmos#8]
Please add a CHANGELOG.md file to make it easier to see what's changed with each release.

**Comment by evgenyneu** [comment]
Good suggestion. I will add the change log file on next update, thanks.

**Comment by evgenyneu** [comment]
Done.
Https://github.com/marketplacer/Cosmos/blob/master/CHANGELOG.md

**Comment by mctavishsolutions** [comment]
Thank you!
